In [ ]:
'''
task: compare scores of multiple algorithms on iris flower dataset using k fold cross classification
'''

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

In [3]:
#logistic regression
logisticRegressionScores = cross_val_score(LogisticRegression(), iris.data, iris.target) #use model, split datasets and do tests
logisticRegressionScores

c:\users\danilo\pycharmprojects\machinelearning1\venv\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [4]:
np.average(logisticRegressionScores)

0.9733333333333334

In [5]:
#decision tree
decisionTreeScores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
decisionTreeScores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [6]:
np.average(decisionTreeScores)

0.9600000000000002

In [7]:
#support vector machine
svmScores = cross_val_score(SVC(), iris.data, iris.target)
svmScores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
np.average(svmScores)

0.9666666666666666

In [9]:
randomForestScores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
randomForestScores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [10]:
np.average(randomForestScores)

0.9666666666666668